<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\EBGaramond-Bold.ttf" />
    <None Remove="Fonts\EBGaramond-BoldItalic.ttf" />
    <None Remove="Fonts\EBGaramond-ExtraBold.ttf" />
    <None Remove="Fonts\EBGaramond-ExtraBoldItalic.ttf" />
    <None Remove="Fonts\EBGaramond-Italic.ttf" />
    <None Remove="Fonts\EBGaramond-Medium.ttf" />
    <None Remove="Fonts\EBGaramond-MediumItalic.ttf" />
    <None Remove="Fonts\EBGaramond-Regular.ttf" />
    <None Remove="Fonts\EBGaramond-SemiBold.ttf" />
    <None Remove="Fonts\EBGaramond-SemiBoldItalic.ttf" />
    <None Remove="Fonts\LiberationSans-Bold.ttf" />
    <None Remove="Fonts\LiberationSans-BoldItalic.ttf" />
    <None Remove="Fonts\LiberationSans-Italic.ttf" />
    <None Remove="Fonts\LiberationSans-Regular.ttf" />
    <None Remove="Images\CarteFavorita.png" />
    <None Remove="Images\Comentarii.png" />
    <None Remove="Images\Dreapta.png" />
    <None Remove="Images\Lupa.png" />
    <None Remove="Images\MarireText.png" />
    <None Remove="Images\ModIntunecat.png" />
    <None Remove="Images\Schita.png" />
    <None Remove="Images\Stinga.png" />
    <None Remove="Images\Trimiteri.png" />
    <None Remove="imagini\menora.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.20.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PdfSharp" Version="6.2.2" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.2" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Speech" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fonts\EBGaramond-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-ExtraBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-ExtraBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-Medium.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-MediumItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-SemiBold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\EBGaramond-SemiBoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\LiberationSans-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\LiberationSans-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\LiberationSans-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Fonts\LiberationSans-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <Resource Include="Images\CarteFavorita.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Comentarii.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Dreapta.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Lupa.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\MarireText.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ModIntunecat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Schita.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Stinga.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Trimiteri.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="imagini\menora.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
